apiVersion: v1
kind: Secret
metadata: # metadata about the secret
  name: innovatech-db-secret
  namespace: innovatech
type: Opaque # type of secret, in this case, opaque means that the data is stored as key-value pairs
data: # data is the actual secret data, encoded in base64
  MYSQL_ROOT_PASSWORD: daskdfiusdhiweb
  MYSQL_APP_USER: innovatech_app
  MYSQL_APP_PASSWORD: daskdfiusdhiweb-innovatech
  MYSQL_DATABASE: innovatech_db
